services:
  gymstats:
    build: .

  influxdb:
    image: influxdb:2
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: admin
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: admin-token
      DOCKER_INFLUXDB_INIT_ORG: gym
      DOCKER_INFLUXDB_INIT_BUCKET: clubs
